/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUploadsRouteImport } from './routes/app.uploads'
import { Route as AppColumnMappingRouteImport } from './routes/app.column-mapping'
import { Route as AppUploadsFileIdRouteImport } from './routes/app.uploads.$fileId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadsRoute = AppUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AppRoute,
} as any)
const AppColumnMappingRoute = AppColumnMappingRouteImport.update({
  id: '/column-mapping',
  path: '/column-mapping',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadsFileIdRoute = AppUploadsFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => AppUploadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/column-mapping': typeof AppColumnMappingRoute
  '/app/uploads': typeof AppUploadsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/uploads/$fileId': typeof AppUploadsFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/column-mapping': typeof AppColumnMappingRoute
  '/app/uploads': typeof AppUploadsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/uploads/$fileId': typeof AppUploadsFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/column-mapping': typeof AppColumnMappingRoute
  '/app/uploads': typeof AppUploadsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/uploads/$fileId': typeof AppUploadsFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/column-mapping'
    | '/app/uploads'
    | '/app/'
    | '/app/uploads/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/column-mapping'
    | '/app/uploads'
    | '/app'
    | '/app/uploads/$fileId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/column-mapping'
    | '/app/uploads'
    | '/app/'
    | '/app/uploads/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/uploads': {
      id: '/app/uploads'
      path: '/uploads'
      fullPath: '/app/uploads'
      preLoaderRoute: typeof AppUploadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/column-mapping': {
      id: '/app/column-mapping'
      path: '/column-mapping'
      fullPath: '/app/column-mapping'
      preLoaderRoute: typeof AppColumnMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/uploads/$fileId': {
      id: '/app/uploads/$fileId'
      path: '/$fileId'
      fullPath: '/app/uploads/$fileId'
      preLoaderRoute: typeof AppUploadsFileIdRouteImport
      parentRoute: typeof AppUploadsRoute
    }
  }
}

interface AppUploadsRouteChildren {
  AppUploadsFileIdRoute: typeof AppUploadsFileIdRoute
}

const AppUploadsRouteChildren: AppUploadsRouteChildren = {
  AppUploadsFileIdRoute: AppUploadsFileIdRoute,
}

const AppUploadsRouteWithChildren = AppUploadsRoute._addFileChildren(
  AppUploadsRouteChildren,
)

interface AppRouteChildren {
  AppColumnMappingRoute: typeof AppColumnMappingRoute
  AppUploadsRoute: typeof AppUploadsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppColumnMappingRoute: AppColumnMappingRoute,
  AppUploadsRoute: AppUploadsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
